name: .NET

on:
  push:
    paths:
      - QuizProject/**
    branches: [ main ]
  pull_request:
    paths:
      - QuizProject/**
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    
    - name: Restore dependencies
      run: dotnet restore
      working-directory: QuizProject/QuizProject
    
    - name: Build
      run: dotnet build --no-restore
      working-directory: QuizProject/QuizProject
    
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: QuizProject/QuizUnitTest
