name: QuizProject .NET

on:
  push:
    paths:
      - QuizProject/**
    branches: [ main ]
  pull_request:
    paths:
      - QuizProject/**
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore
    
    - name: Test
      run: dotnet test --verbosity normal
